## Load the Libraries

In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

## Load the Data

In [109]:
data =pd.read_csv('1.02.+Multiple+linear+regression.csv')
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [110]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Create the Miltiple Linear Regression

### Declare the Dependant and Independant Variables

In [111]:
x=data[['SAT', 'Rand 1,2,3']]
y=data['GPA']

## Regression itself

In [112]:
reg = LinearRegression()

In [113]:
reg.fit(x,y)

LinearRegression()

In [114]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [115]:
reg.intercept_

0.29603261264909486

## Calculating the Adjusted R-squared

In [116]:
reg.score(x,y)

0.40668119528142843

## Formula for Adjusted R⌃2
$R⌃2_{adj.}=1-(1-R⌃2)*\frac{n-1}{n-p-1}$

In [117]:
x.shape

(84, 2)

In [118]:
r2= reg.score(x,y)
n=x.shape[0]
p=x.shape[1]
adjusted_r2= 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

### Check against stats modals summary

In [119]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

### 1st Array = F statistic     2nd Array = P Value  ( Use  P values [1])

In [120]:
p_values=f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [121]:
p_values.round(3)

array([0.   , 0.676])

### P values over .5 useless (Rand 1,2,3 useless)  P-value is best way to determine if a variable is redundant

## Creating a Summary table - sklearn

In [122]:
reg_summary = pd.DataFrame(data=x.columns.values, columns = ['Features'] )
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [125]:
reg_summary ['Coefficents']=reg.coef_
reg_summary ['p-values']=p_values.round(3)


In [126]:
reg_summary

Features  Coefficents  p-values
0         SAT     0.001654     0.000
1  Rand 1,2,3    -0.008270     0.676

## Standardisation

In [134]:
from sklearn.preprocessing import StandardScaler

In [135]:
scaler = StandardScaler()

### scaler subtracts mean and devides by standard deviation

In [136]:
scaler.fit(x)

StandardScaler()

In [138]:
x_scaled=scaler.transform(x)

In [139]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

## Regression with scaled features 

In [141]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [142]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [143]:
reg.intercept_

3.330238095238095

## Summary Table 

In [148]:
reg_summary= pd.DataFrame([['Bias'],['SAT'], ['Rand 1,2,3']], columns = ['Features'])
reg_summary['Weights']=reg.intercept_, reg.coef_[0], reg.coef_[1]


In [149]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

## Making predictions with standardises coeficiants (weights)

In [157]:
new_data = pd.DataFrame(data =[[1700,2],[1800,1]],columns =['SAT', 'Rand 1,2,3'])

In [158]:
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [159]:
reg.predict(new_data)

/Users/leewilson/anaconda3/lib/python3.11/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [161]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [162]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])